# Copyright (c) 2026 maker374
# https://github.com/maker374/xodata
# Apache License 2.0
# Updated 2024-07-13

from __future__ import annotations

import datetime
from decimal import ROUND_HALF_UP, Decimal
import json
from dataclasses import dataclass, field
from email import policy
from email.message import Message
from email.parser import BytesParser
from time import perf_counter
from typing import Any, Mapping, Sequence, TypeAlias
from uuid import uuid4

from requests import Request, RequestException, Response, Session
from requests.structures import CaseInsensitiveDict

PartRequest: TypeAlias = "Request | BatchRequest"
PartResponse: TypeAlias = "Response | BatchResponse"

class BatchError(Exception):
    """Raised when a batch payload or response is invalid."""

def _parse_content_type(value: str) -> tuple[str, dict[str, str]]:
    message = Message()
    message["content-type"] = value
    content_type = message.get_content_type()
    params: dict[str, str] = {}
    for key, param_value in message.get_params(header="content-type"):
        if key.lower() != "content-type":
            params[key.lower()] = str(param_value)
    return content_type.lower(), params

def _new_boundary(prefix: str) -> str:
    return f"{prefix}_{uuid4().hex}"

def _normalize_newlines(value: str) -> str:
    return value.replace("\r\n", "\n").replace("\r", "\n")

def _ensure_bytes(value: bytes | bytearray | str | None) -> bytes:
    if value is None:
        return b""
    if isinstance(value, (bytes, bytearray)):
        return bytes(value)
    return str(value).encode("utf-8")

def _decimal_6(value):
    return Decimal(str(value)).quantize(Decimal("0.000001"), rounding=ROUND_HALF_UP)

@dataclass(slots=True)
class BatchRequest:
    """Represents an OData batch request or nested changeset."""

    parts: list[PartRequest] = field(default_factory=list)
    sources: list[Any] = field(default_factory=list)
    boundary: str = ""
    started_at: datetime.datetime = field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))
    finished_at: datetime.datetime = field(init=False)
    max_parts: int | None = None
    max_threads: int = 1 # For logging and stats purposes only.
    step_name: str | None = None # For logging and stats purposes only.
    post_count: int = field(default=0, init=False, repr=False)
    total_parts: int = field(default=0, init=False, repr=False)
    error_parts: int = field(default=0, init=False, repr=False)
    _last_auto_report_bucket: int | None = field(default=None, init=False, repr=False)
    _boundary_autogenerated: bool = field(default=False, init=False, repr=False)

    def __post_init__(self) -> None:
        if not self.boundary:
            self.boundary = _new_boundary("B")
            self._boundary_autogenerated = True
        self.finished_at = self.started_at

    @staticmethod
    def with_config(of: "BatchRequest") -> "BatchRequest":
        """Create a new BatchRequest with the same configuration as another."""
        return BatchRequest(
            max_parts=of.max_parts,
            max_threads=of.max_threads,
            step_name=of.step_name
        )

    @property
    def total_elapsed_time(self) -> float:
        return max((self.finished_at - self.started_at).total_seconds(), 0.0)

    def append(self, part: PartRequest, source: Any = None) -> None:
        if self.max_parts is not None and self.part_count + 1 > self.max_parts:
            raise BatchError(f"Batch request part limit exceeded: limit={self.max_parts}")
        if isinstance(part, BatchRequest) and part._boundary_autogenerated and part.boundary.startswith("B_"):
            part.boundary = _new_boundary("C")
        self.parts.append(part)
        self.sources.append(source)

    def clear_parts(self) -> None:
        self.parts.clear()
        self.sources.clear()
    
    def add_stats(self, to: BatchRequest, auto_print_stats_interval: int = 0) -> None:
        to.step_name = to.step_name or self.step_name
        to.max_parts = self.max_parts if to.max_parts is None else None if self.max_parts is None else min(to.max_parts, self.max_parts)
        to.max_threads = max(to.max_threads, self.max_threads)
        to.post_count += self.post_count
        to.total_parts += self.total_parts
        to.error_parts += self.error_parts
        to.started_at = min(to.started_at, self.started_at)
        to.finished_at = max(to.finished_at, self.finished_at)
        to.auto_print_stats(interval=auto_print_stats_interval)

    def report_stats(
        self, print_stats: bool = True, final_stats: bool = True, stats_separator: str = "; "
    ) -> dict[str, int | float | datetime.datetime]:
        stats: dict[str, int | float | datetime.datetime] = {
            "step_name": self.step_name or "",
            "batch_size_config": self.max_parts or 0,
            "thread_count_config": self.max_threads,
            "posted_batch_count": self.post_count,
            "total_request_count": self.total_parts,
            "failed_request_count": self.error_parts,
            "total_elapsed_seconds": _decimal_6(self.total_elapsed_time),
            "average_batch_seconds": _decimal_6(self.average_time_per_post),
            "average_request_seconds": _decimal_6(self.average_time_per_part),
            "started_at_datetime": self.started_at,
            "finished_at_datetime": self.finished_at,
        }
        if print_stats:
            lines = [
                f"posted_batch_count: {self.post_count}",
                f"total_request_count: {self.total_parts}",
                f"failed_request_count: {self.error_parts}",
                f"total_elapsed_seconds: {self.total_elapsed_time:.6f} seconds",
                f"average_batch_seconds: {self.average_time_per_post:.6f} seconds",
                f"average_request_seconds: {self.average_time_per_part:.6f} seconds",
            ]
            if (final_stats):
                lines.insert(0, f"thread_count_config: {self.max_threads}")
                lines.insert(0, f"batch_size_config: {self.max_parts or 0}")
                lines.append(f"started_at_datetime: {self.started_at.isoformat()}")
                lines.append(f"finished_at_datetime: {self.finished_at.isoformat()}")
            progress_prefix = "Progress: " if not final_stats else ""
            print(progress_prefix + stats_separator.join(lines))
        return stats

    def auto_print_stats(self, interval: int) -> None:
        if interval > 0:
            current_bucket = (int(self.total_elapsed_time) // interval) * interval
            if self._last_auto_report_bucket != current_bucket:
                self._last_auto_report_bucket = current_bucket
                if current_bucket > 0:
                    self.report_stats(print_stats=True, final_stats=False, stats_separator="; ")

    def _record_post(self, posted_part_count: int, failed_part_count: int, elapsed_seconds: float) -> None:
        self.post_count += 1
        self.total_parts += posted_part_count
        self.error_parts += failed_part_count
        self.finished_at += datetime.timedelta(seconds=elapsed_seconds)

    @property
    def part_count(self) -> int:
        return len(self.parts)

    @property
    def is_full(self) -> bool:
        return self.max_parts is not None and self.part_count >= self.max_parts

    @property
    def content_type(self) -> str:
        return f"multipart/mixed; boundary={self.boundary}"

    @property
    def average_time_per_post(self) -> float:
        return self.total_elapsed_time / self.post_count if self.post_count else 0.0

    @property
    def average_time_per_part(self) -> float:
        return self.total_elapsed_time / self.total_parts if self.total_parts else 0.0

    def to_multipart_mixed(self) -> bytes:
        return format_batch_request(self)

@dataclass(slots=True)
class BatchResponse:
    """Represents an OData batch response or nested changeset response."""

    parts: list[PartResponse] = field(default_factory=list)
    boundary: str = ""
    max_parts: int | None = None

    @property
    def part_count(self) -> int:
        return len(self.parts)

    def append(self, part: PartResponse) -> None:
        if self.max_parts is not None and self.part_count + 1 > self.max_parts:
            raise BatchError(f"Batch response part limit exceeded: limit={self.max_parts}")
        self.parts.append(part)

def _format_request_headers(headers: Mapping[str, str] | None) -> list[str]:
    if not headers:
        return []
    return [f"{key}: {value}" for key, value in headers.items()]

def _request_body_bytes(request: Request) -> bytes:
    if request.json is not None:
        payload = json.dumps(request.json, separators=(",", ":"))
        return payload.encode("utf-8")
    return _ensure_bytes(request.data)

def _format_application_http_request(request: Request) -> bytes:
    method = (request.method or "GET").upper()
    url = request.url or ""
    lines = [f"{method} {url} HTTP/1.1"]
    lines.extend(_format_request_headers(request.headers))
    body = _request_body_bytes(request)
    if request.json is not None and not any(k.lower() == "content-type" for k in (request.headers or {})):
        lines.append("Content-Type: application/json")
    payload = "\r\n".join(lines).encode("utf-8") + b"\r\n\r\n"
    if body:
        payload += body
    return payload

def _format_multipart_part_request(part: PartRequest) -> bytes:
    if isinstance(part, BatchRequest):
        nested_payload = format_batch_request(part)
        header = (
            "Content-Type: "
            + part.content_type
            + "\r\n"
            + "Content-Transfer-Encoding: binary\r\n\r\n"
        )
        return header.encode("utf-8") + nested_payload
    if isinstance(part, Request):
        header = "Content-Type: application/http\r\nContent-Transfer-Encoding: binary\r\n\r\n"
        return header.encode("utf-8") + _format_application_http_request(part)
    raise TypeError(f"Unsupported batch request part type: {type(part)!r}")

def format_batch_request(batch: BatchRequest) -> bytes:
    """Format a batch request as multipart/mixed payload bytes."""
    boundary = batch.boundary
    chunks: list[bytes] = []
    for part in batch.parts:
        chunks.append(f"--{boundary}\r\n".encode("utf-8"))
        chunks.append(_format_multipart_part_request(part))
        chunks.append(b"\r\n")
    chunks.append(f"--{boundary}--\r\n".encode("utf-8"))
    return b"".join(chunks)

def _split_http_message(payload: bytes) -> tuple[list[str], bytes]:
    text = payload.decode("latin1")
    normalized = _normalize_newlines(text)
    marker = "\n\n"
    index = normalized.find(marker)
    if index < 0:
        return normalized.split("\n"), b""
    header_block = normalized[:index]
    body_text = normalized[index + len(marker) :]
    return header_block.split("\n"), body_text.encode("latin1")

def _parse_headers(lines: Sequence[str]) -> CaseInsensitiveDict:
    headers: CaseInsensitiveDict = CaseInsensitiveDict()
    for line in lines:
        line = line.strip()
        if not line:
            continue
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        headers[key.strip()] = value.strip()
    return headers

def _parse_application_http_response(payload: bytes) -> Response:
    lines, body = _split_http_message(payload)
    if not lines or not lines[0].startswith("HTTP/"):
        raise BatchError("Invalid application/http payload: missing HTTP status line")
    status_line = lines[0].strip().split(" ", 2)
    if len(status_line) < 2:
        raise BatchError("Invalid HTTP status line in batch response")
    response = Response()
    response.status_code = int(status_line[1])
    response.reason = status_line[2] if len(status_line) > 2 else ""
    response.headers = _parse_headers(lines[1:])
    response._content = body
    response.encoding = response.encoding or "utf-8"
    return response

def _parse_message_part(part_message) -> PartResponse:
    content_type = part_message.get_content_type().lower()
    if content_type == "application/http":
        payload = part_message.get_payload(decode=True)
        if payload is None:
            payload = b""
        return _parse_application_http_response(payload)
    if content_type == "multipart/mixed":
        boundary = part_message.get_param("boundary")
        nested = BatchResponse(boundary=boundary or "")
        for nested_part in part_message.iter_parts():
            nested.append(_parse_message_part(nested_part))
        return nested
    raise BatchError(f"Unsupported batch response part content type: {content_type}")

def parse_batch_response(content_type: str, body: bytes | bytearray | str) -> BatchResponse:
    """Parse a multipart/mixed OData batch response into Response objects."""
    parsed_type, params = _parse_content_type(content_type)
    if parsed_type != "multipart/mixed":
        raise BatchError(f"Expected multipart/mixed response, got {parsed_type}")
    boundary = params.get("boundary")
    if not boundary:
        raise BatchError("multipart/mixed response missing boundary parameter")
    payload = _ensure_bytes(body)
    envelope = (
        f"Content-Type: multipart/mixed; boundary={boundary}\r\nMIME-Version: 1.0\r\n\r\n".encode(
            "utf-8"
        )
        + payload
    )
    message = BytesParser(policy=policy.default).parsebytes(envelope)
    parsed = BatchResponse(boundary=boundary)
    for part in message.iter_parts():
        parsed.append(_parse_message_part(part))
    return parsed

def _count_error_response_parts(response: BatchResponse) -> int:
    error_count = 0
    for part in response.parts:
        if isinstance(part, Response):
            if part.status_code >= 300: # since we don't follow redirects here, they are an error in the context of a batch response
                error_count += 1
        elif isinstance(part, BatchResponse):
            error_count += _count_error_response_parts(part)
    return error_count

def post_batch_request(
    service_root_url: str,
    session: Session,
    request: BatchRequest,
    auto_print_stats_interval: int = 0,
    check_response_part_count: bool = True,
    odata_continue_on_error: bool = True,
    send_single_as_unbatched: bool = False,
    cascade_failure_to_parts: bool = False
) -> BatchResponse:
    """Send a batch request through a requests Session and parse the response."""
    if cascade_failure_to_parts:
        try:
            return post_batch_request(
                service_root_url=service_root_url,
                session=session,
                request=request,
                auto_print_stats_interval=auto_print_stats_interval,
                check_response_part_count=check_response_part_count,
                odata_continue_on_error=odata_continue_on_error,
                send_single_as_unbatched=send_single_as_unbatched,
                cascade_failure_to_parts=False
            )
        except RequestException as error:
            failed = BatchResponse(max_parts=request.max_parts)
            response = error.response if error.response is not None else Response()
            if response.status_code == 0:
                response.status_code = 900
                response.reason = str(error)
            for _ in request.parts:
                failed.append(response)
            return failed
    start_time = perf_counter()
    posted_part_count = 0
    failed_part_count = 0
    headers = {
        "Content-Type": request.content_type,
        "Accept": "multipart/mixed",
    }
    if odata_continue_on_error:
        headers["Prefer"] = "odata.continue-on-error"
    try:
        if send_single_as_unbatched:
            if request.part_count != 1:
                raise BatchError(
                    "send_single_as_unbatched=True requires exactly one batch request part"
                )
            single_part = request.parts[0]
            if not isinstance(single_part, Request):
                raise BatchError(
                    "send_single_as_unbatched=True requires the single part to be a Request"
                )
            method = (single_part.method or "GET").upper()
            part_url = single_part.url or ""
            if part_url.startswith(("http://", "https://")):
                target_url = part_url
            else:
                target_url = service_root_url.rstrip("/") + "/" + part_url.lstrip("/")
            response = session.request(
                method=method,
                url=target_url,
                headers=single_part.headers,
                data=single_part.data,
                json=single_part.json,
            )
            response.raise_for_status()
            parsed = BatchResponse(max_parts=request.max_parts)
            parsed.append(response)
            posted_part_count = 1
            failed_part_count = 1 if response.status_code >= 300 else 0 # since we don't follow redirects here, they are an error in the context of a batch response
            return parsed
        else:
            batch_url = service_root_url.rstrip("/") + "/$batch"
            response = session.post(
                batch_url,
                data=request.to_multipart_mixed(),
                headers=headers,
            )
            response.raise_for_status()
            content_type = response.headers.get("Content-Type")
            if not content_type:
                raise BatchError("Batch response missing Content-Type header")
            parsed = parse_batch_response(content_type, response.content)
            parsed.max_parts = request.max_parts
            posted_part_count = request.part_count
            failed_part_count = _count_error_response_parts(parsed)
            if check_response_part_count and len(parsed.parts) != len(request.parts):
                raise BatchError(
                    f"Batch response part count mismatch: expected {len(request.parts)}, received {len(parsed.parts)}"
                )
            return parsed
    finally:
        request._record_post(posted_part_count, failed_part_count, perf_counter() - start_time)
        request.auto_print_stats(interval=auto_print_stats_interval)

__all__ = [
    "BatchError",
    "BatchRequest",
    "BatchResponse",
    "format_batch_request",
    "parse_batch_response",
    "post_batch_request",
]
